var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/players/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x9p3qk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_054w6h4.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p15_7-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kl59ms._.js")
R.c("server/chunks/ssr/_0ffurmj._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_1863-sq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_players_page_actions_0u3f1nq.js")
R.m(56491)
module.exports=R.m(56491).exports
